SELECT FILA.NUFILAPROC, FILA.NUTIPOPROC, FILA.CHAVE,TIPO.NOME
FROM MGSTCTFILAPROC FILA
 INNER JOIN MGSTCTTIPOPROC TIPO ON TIPO.NUTIPOPROC = FILA.NUTIPOPROC
WHERE STATUS = 'I'
AND ROWNUM <= :QTDEXECFILA
AND NUTIPOPROC NOT IN( 13, 15, 16, 17, 22, 24, 25 )