SELECT FILA.NUFILAPROC, FILA.NUTIPOPROC, FILA.CHAVE,TIPO.NOME
FROM MGSTCTFILAPROC FILA
 INNER JOIN MGSTCTTIPOPROC TIPO ON TIPO.NUTIPOPROC = FILA.NUTIPOPROC
WHERE STATUS = 'I'
AND ROWNUM <= :QTDEXECFILA