SELECT FILA.NUFILAPROC, FILA.NUTIPOPROC, FILA.CHAVE,TIPO.NOME
FROM MGSTCTFILAPROC FILA
         INNER JOIN MGSTCTTIPOPROC TIPO ON TIPO.NUTIPOPROC = FILA.NUTIPOPROC
WHERE FILA.STATUS = 'I'
  AND ROWNUM <= :QTDEXECFILA
AND FILA.NUTIPOPROC NOT IN( 13, 15, 16, 17, 22, 24, 25 )