UPDATE MGSTCTLCTCUSTO SET NURLTANEXO = :NURLTANEXO 
WHERE NUMCONTRATO = :NUMCONTRATO
AND CODTIPOFATURA = :CODTIPOFATURA
AND CODUNIDADEFATUR = :CODUNIDADEFATUR
AND DTLANCCUSTO = :DTLANCCUSTO
AND TIPGESTOR = :TIPGESTOR