UPDATE   MGSTCTEVTMENSAL
   SET   TIPLANCEVENTO = 'M',
         CODUNIDADEFATURANT = CODUNIDADEFATUR,
         DTUNIDADEFATURANT = SYSDATE,
         CODUNIDADEFATUR = :V_UNIDADE,
         DTALTERLANC = SYSDATE,
         CODUSUALTERLANC = :LOGIN
 WHERE   NUEVTMENSAL = :V_NUEVTMENSAL AND CODINTEGRACAOLC IS NULL