UPDATE   MGSTCTEVTMENSAL
   SET   TIPLANCEVENTO = 'M',
         DTLCCUSTO = :V_DTLCCUSTO,
         DTALTERLANC = SYSDATE,
         CODUSUALTERLANC = :LOGIN
 WHERE   NUEVTMENSAL = :V_NUEVTMENSAL AND CODINTEGRACAOLC IS NULL