UPDATE   MGSTCTEVTMENSAL
   SET   TIPLANCEVENTO = 'M',
         CODSITLANC = :V_SIT,
         DTALTERLANC = SYSDATE,
         CODUSUALTERLANC = :LOGIN
 WHERE   NUEVTMENSAL = :V_NUEVTMENSAL AND CODINTEGRACAOLC IS NULL