SELECT
:VALOR_DIGITADO + (:VALOR_DIGITADO * ((SUBSTR(BUSCA_TAXA_INCIDENCIA(:UNIDADEFATURAMENTO,:CODTIPOFATURA,'F'),1,6)*1 +
SUBSTR(BUSCA_TAXA_INCIDENCIA(:UNIDADEFATURAMENTO,:CODTIPOFATURA,'F'),1,6)*1) /100 ))
1
AS VALOR
FROM DUAL

