SELECT NUCONTREVENTO FROM (
SELECT NUCONTREVENTO, NROOCORRENCIA, MAX(NROOCORRENCIA) OVER() AS MAXNROOCORRENCIA
FROM MGSTCTCONTRVLRPS
WHERE NUMCONTRATO = :NUMCONTRATO
AND CODTPN = :CODTPN
AND CODTIPOPOSTO = :CODTIPOPOSTO
AND CODEVENTO = :CODEVENTO
AND TRUNC(SYSDATE) BETWEEN TRUNC(DTINICIO) AND TRUNC(DTFIM)
AND ALIQISS = 0
) WHERE NROOCORRENCIA = MAXNROOCORRENCIA