SELECT
:VALOR_DIGITADO + (:VALOR_DIGITADO * ((SUBSTR(NVL( BUSCA_TAXA_INCIDENCIA(:UNIDADEFATURAMENTO,:CODTIPOFATURA,'F'), 0 ),1,7)*1 ) /100 ))
AS VALOR
, (SUBSTR(NVL( BUSCA_TAXA_INCIDENCIA(:UNIDADEFATURAMENTO,:CODTIPOFATURA,'F'), 0 ),1,7)*1)/100 AS TAXA
, ((SUBSTR(NVL( BUSCA_TAXA_ADMINISTRACAO(:UNIDADEFATURAMENTO,:CODTIPOFATURA,'F'), 0 ),1,7)*1)/100) TAXA_ADM
,
(:VALOR_DIGITADO + (:VALOR_DIGITADO * ((SUBSTR(NVL( BUSCA_TAXA_INCIDENCIA(:UNIDADEFATURAMENTO,:CODTIPOFATURA,'F'), 0 ),1,7)*1 ) /100 ))) *
((SUBSTR(NVL( BUSCA_TAXA_ADMINISTRACAO(:UNIDADEFATURAMENTO,:CODTIPOFATURA,'F'), 0 ),1,7)*1)/100)
+
(:VALOR_DIGITADO + (:VALOR_DIGITADO * ((SUBSTR(NVL( BUSCA_TAXA_INCIDENCIA(:UNIDADEFATURAMENTO,:CODTIPOFATURA,'F'), 0 ),1,7)*1 ) /100 )))

VALOR_GERAL
FROM DUAL

