SELECT DISTINCT CODUNIDADEFATUR CODSITE
FROM MGSTCTLCTCUSTO
WHERE TIPGESTOR = 'G'
AND CODTIPOFATURA = :CODTIPOFATURA
AND DTLANCCUSTO = :DTLANCCUSTO
AND CODUNIDADEFATUR >= :CODSITEI
AND CODUNIDADEFATUR <= :CODSITEF