SELECT DISTINCT MESRELATORIO AS MESRELATORIO
, CODUNIDADEFATUR, CODTIPOFATURA, NUMCONTRATO
FROM MGSTCTRLTANEXOCAD
WHERE CODUNIDADEFATUR = :CODUNIDADEFATUR OR :CODUNIDADEFATUR = 0 OR :CODUNIDADEFATUR IS NULL