SELECT MAX(NUCONTRMATSRV) AS NUCONTRMATSRV
FROM MGSTCTCONTRVLRSERV
WHERE NUMCONTRATO = :NUMCONTRATO
AND NUMODALIDADE = :NUMODALIDADE
AND CODSERVMATERIAL = :CODSERVMATERIAL
AND CODEVENTO = :CODEVENTO
AND TRUNC(SYSDATE) BETWEEN DTINICIO AND DTFIM
AND ALIQADM = 0