SELECT NUCONTRMATSRV FROM (
SELECT NUCONTRMATSRV, NROOCORRENCIA, MAX(NROOCORRENCIA) OVER() AS MAXNROOCORRENCIA
FROM MGSTCTCONTRVLRSERV
WHERE NUMCONTRATO = :NUMCONTRATO
AND CODTPN = :CODTPN
AND CODSERVMATERIAL = :CODSERVMATERIAL
AND CODEVENTO = :CODEVENTO
AND TRUNC(SYSDATE) BETWEEN TRUNC(DTINICIO) AND TRUNC(DTFIM)
AND ALIQISS = 0
) WHERE NROOCORRENCIA = MAXNROOCORRENCIA