SELECT NUCONTRMATSRV FROM (
SELECT NUCONTRMATSRV, NROOCORRENCIA, MAX(NROOCORRENCIA) OVER() AS MAXNROOCORRENCIA
FROM MGSTCTCONTRVLRSERV
WHERE NUMCONTRATO = :NUMCONTRATO
AND CODTPN = :CODTPN
AND CODSERVMATERIAL = :CODSERVMATERIAL
AND CODEVENTO = :CODEVENTO
AND TRUNC(SYSDATE) BETWEEN TRUNC(DTINICIO) AND TRUNC(DTFIM)
AND ALIQISS = ( NVL(SUBSTR(busca_tributos(:v_codunidadefatura,:v_codtipofatura,'F'),11,5)+0,0)*1 )
) WHERE NROOCORRENCIA = MAXNROOCORRENCIA